spring:
  application:
    name: news
#  zipkin:
#    base-url: http://localhost:8050
  rabbitmq:
    host: 172.18.115.41
    port: 5672
    username: guest
    password: guest
  sleuth:
    sampler:
      percentage: 1.0
server:
  port: 8201
restApi:
  swagger:
    title: springdemo-新闻webapi
    version: 1
    description: 新闻webapi!！！
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8080/eureka/
ribbon:
  ConnectTimeout: 1000
  ReadTimeout: 1000
  MaxAutoRetries: 1
  MaxAutoRetriesNextServer: 2
  OkToRetryOnAllOperations: true
hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 3000
feign:
  hystrix:
    enabled: true
  compression:
    request:
      enabled: true
      mime-types: text/xml,application/xml,application/json
      min-request-size: 2048
    response:
      enabled: true
