spring:
  application:
    name: turbine
server:
  port: 8050
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8080/eureka/
turbine:
  combine-host-port: true
  clusterNameExpression: "'default'"
  app-config: news
