spring:
#  zipkin:
#    base-url: http://localhost:8050
  application:
    name: user-v1
  rabbitmq:
    host: 172.18.115.41
    port: 5672
    username: guest
    password: guest
  sleuth:
    sampler:
      percentage: 1.0
server:
  port: 8091
restApi:
  swagger:
    title: springdemo-用户webapi
    version: 1
    description: 用户webapi!!!!
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8080/eureka/
management:
  security:
    enabled: false