spring:
  application:
    name: gateway
server:
  port: 8070
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8080/eureka/
management:
  security:
    enabled: false
zuul:
  retryable: true