FROM java:8

MAINTAINER liurui<1313475@qq.com>

WORKDIR /data

EXPOSE 8080

ADD target/spring-cloud-demo-eureka-server-0.0.1-SNAPSHOT.jar ./

CMD ["java", "-jar", "spring-cloud-demo-eureka-server-0.0.1-SNAPSHOT.jar"]